version: '2'
services:
  postgresql:
    container_name: postgresql
    image: postgres:9.6-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: jp_user
      POSTGRES_PASSWORD: jp_pass
      POSTGRES_DB: jp_db
    volumes:
      - "/postgresql/data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    links:
      - postgresql
    ports:
      - 5050:80

  redis:
    container_name: redis
    image: redis:4-alpine
    restart: always
    ports:
      - 6379:6379